### ISSUE TITLE
Cannot call `useEffect` in preview component

### ISSUE THREAD

**Issue by klapec** [sofn-xyz/mailing#276]
**Describe the bug**
I wish to be able to call `useEffect` in my code, particularly in the preview `./emails/previews/Foo.tsx` component. I'm not able though - I'm getting this error:
```
@org/mailing:dev: error - ../../../node_modules/react/cjs/react.development.js (1634:0) @ useEffect
@org/mailing:dev: error - TypeError: Cannot read properties of null (reading 'useEffect')
@org/mailing:dev:     at useEffect (webpack-internal:///../../../node_modules/react/cjs/react.development.js:1635:21)
@org/mailing:dev:     at Object.Preview (webpack-internal:///./src/moduleManifest.js:663:76)
@org/mailing:dev:     at getPreviewComponent (webpack-internal:///./src/util/moduleManifestUtil.ts:24:43)
@org/mailing:dev:     at getStaticProps (webpack-internal:///./src/pages/previews/[[...path]].tsx:53:104)
@org/mailing:dev:     at Object.renderToHTML (/Volumes/Dev/repos/org-frontend-monorepo/node_modules/next/server/render.tsx:749:20)
@org/mailing:dev:     at runMicrotasks (<anonymous>)
@org/mailing:dev:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@org/mailing:dev:     at doRender (/Volumes/Dev/repos/org-frontend-monorepo/node_modules/next/server/base-server.ts:1288:30)
@org/mailing:dev:     at cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/Volumes/Dev/repos/org-frontend-monorepo/node_modules/next/server/base-server.ts:1429:24)
@org/mailing:dev:     at /Volumes/Dev/repos/org-frontend-monorepo/node_modules/next/server/response-cache/index.ts:117:28 {
@org/mailing:dev:   page: '/previews/[[...path]]'
@org/mailing:dev: }
```

**To Reproduce**

1. Create a preview component for a template
2. Add `import { useEffect } from 'react';`
3. Call
```
useEffect(() => {
    console.log(1);
  }, []);
```
within preview component's body
4. Crash

**Expected behavior**
Calling hooks should be allowed.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macos@12.5.1
- Browser [e.g. chrome, safari] irrelevant but Chrome@106.0.5249.119
- Version [e.g. 22] 0.8.7

**Comment by psugihara** [comment]
Thanks for making an issue!

Effects are not supported because we just perform a single render to html and send the result. The component is never "mounted" exactly and props never change on the client because the client just gets html.

What would you like the effect to do? Perhaps we can brainstorm another way to accomplish what you're trying to do.

**Comment by psugihara** [comment]
Oh, that's a neat use-case I've never thought of.

I don't think there's a way to accomplish this currently, but we've had a few requests for being able to edit props in the GUI and I'd like to support it.

For your use-case it sounds like we need...
1. an easy way to edit props in the GUI
2. a way to do something with those props before rendering

Feature 1 needs some design (@monicakogler <3) but we should just do it.

Hooks would be a nice way to do (2) but I'm a bit scared of mucking with mjml-react. It looks like [this person](https://github.com/janus-reith/mjml-react-browser) got it to work but I kind of want the rendered email to use the exact html we're sending.

Another possibility for (2) would be to allow for async preview functions and let you edit the arguments of the preview functions via the GUI. This might be nice because you could control which fields are editable and we could generate input UI based on types.


```tsx
export async function offerBlast(reservationId: string) {

  const response = await fetch(`https://bookbook.com/api/reservation/${reservationId}`);
  const reservation = await response.json();

  return (
    <Offer
      reservation={reservation}
    />
  );
}
```



One more thought...

> URL character limit

https://github.com/sofn-xyz/mailing/issues/136 would solve and I'm happy to prioritize if you want to go that route instead.
 It's p2 right now because I don't think anyone uses it really :). I agree this is not the user friendly direction.

**Comment by klapec** [comment]
I've seen https://github.com/sofn-xyz/mailing/issues/136 and I think it would indeed solve my issue - I'd be able to create a separate page within my main Next.js app that would talk with the _mailing_ API and allow the user to generate html (and even then preview it) based on some arbitrary data passed in via POST request body as the email template props. That should actually work just fine for us! 🙂

**Comment by psugihara** [comment]
Ok sounds good! We'll get that into tomorrow's release. Should be quick. I'll ping back on this thread once it's released.

**Comment by alexfarrill** [comment]
@klapec I just release 0.8.8 which supports POST to the /api/render method.  Hopefully this unblocks you!  Let us know

**Comment by klapec** [comment]
@alexfarrill I can confirm your change works as expected. Thank you for the blazing fast🚀 response! 🙂

**Comment by psugihara** [comment]
hell yes. ty @alexfarrill !

**Comment by psugihara** [comment]
Hey @davidgustys! Awesome to hear you guys are finding mailing useful. Chime in here https://github.com/sofn-xyz/mailing/discussions/121 if you have a minute. I'd love to understand use-cases better to prioritize the backlog.

In theory I would like to support hooks, but don't have a clear idea of how we'd do it simply. Beyond what you mention, another advantage of doing rendering in the browser would be easier debugging using react developer tools. That said, there is one big disadvantage / risk: the html you see in the browser might differ from the statically rendered HTML that is sent in emails if you allow hooks to perform updates after the initial render like with normal react. Currently the html in the browser preview is *exactly* the same html that is used in sending emails which gives me some peace of mind ☺️.

> I initially wanted to use context with brand details, to later consume deeper in the component tree.

I would recommend using a file with constants exported for this (e.g. [theme.ts](https://github.com/sofn-xyz/mailing/blob/main/packages/cli/src/generator_templates/ts/emails/components/theme.ts)) and/or composing components. Since the templates must statically compile to HTML this should give you all of the same capabilities as a context object.

> mjml-browser

Yes there could be a good solution using mjml-browser but I think it would have to be integrated with mjml-react, not mailing directly. We don't do mjml rendering directly but instead defer to mjml-react to render react -> mjml -> html. You could bring up this issue in [the new fork](https://github.com/Faire/mjml-react) to get their take as well (see where we call it in [mjml.ts](https://github.com/sofn-xyz/mailing/blob/main/packages/core/src/mjml.ts#L2)).

**Comment by davidgustys** [comment]
Hi @psugihara, sorry for the late reply, I had an extended weekend. 

First of all, thank you for your prompt response. 

As mentioned, currently because of your product requirements the "theme" changes based on "templateID"/"brandID" and because of that we are still kinda stateful. Having react context would allow us to basically have nicer less repeating code, and we would avoid the need of passing the "ID" down the component tree. 

I understand your concerns and the "clean" approach you are trying to archive without allowing React to have a "state".
But for us having the ability to compose emails the react way (having Initial State) + the nice "Preview" feature provided is the main selling point of using "mailing".

I'm not sure if you have used "next.js" or other similar frameworks before, I think of Initial email rendering as SSR side which does allow initial context; and Preview feature as Client Side.

I'm getting a bit carried away here. For now, we will stick with the strategy of passing the brandID down the component tree, and later experiment with "replacing"/"overriding" `mjml-react` with `mjml-browser` they seem to have the same API, maybe it will just work out of the box.

**Comment by psugihara** [comment]
Sounds good. Interested to hear about any good patterns you find as you use Mailing. Also interested in what you find with `mjml-browser` if you end up going in that direction. I'd like to add it as an option but I'm not sure how we'd do that.

I have used Next extensively, in fact Mailing uses it internally to render the UI in the preview server (but not the email previews because they use the mjml renderer). SSR is a good analog -- all emails must be SSR because no js executes in email clients. So for the simplicity of having one rendering pipeline and to achieve a realistic email client simulation in the previewer, no hooks will run because the react is rendered server-side. This way your preview is 100% the same if you use sendMail to deliver the email to a user or `mailing export-previews` to export as html.

That said, I hear what you're saying with regards to context and avoiding the need to thread your ID down the component tree and I wish we had a better solution.
