### ISSUE TITLE
Streamline CMS > Mailing > CRM

### ISSUE THREAD

**Issue by jbtheard** [sofn-xyz/mailing#348]
**Is your feature request related to a problem? Please describe.**
For people managing their emails in a CMS, there is a lot of copy and paste involved:
- take the subject + preheader from CMS and paste it into the CRM
- take the html code from Mailing and paste in into the CRM

**Describe the solution you'd like**
I actually have 2, possibly unrelated suggestions:
- ability to handle Subject and Preheader, somehow.
- ability to POST html to a predefined url

**Additional context**
For Subject line (and pre header, should we want to manage that), I understand it's of no value for people just looking to build html but it's of value for people extracting data from a system (here, CMS).
It could be as simple as a prop in the component, that would add a button in the interface header "copy subject line".
If/when posting to an external system (here CRM), it would be a must have to update email subject together with body.
Also, it could be used when sending the test email (keeping name of template in brackets for instance)

**Comment by psugihara** [comment]
👍 thanks for the issue! Subject handling is on my radar. I think a good way to do it would be an optional function on the template. This way the template code all lives in one place for that email.

Then `sendMail` could use this if no subject were passed into a `sendMail` call and we could render it when rendering a preview.

We could do the same with preheader.

```tsx
MyTemplate.subject = (props: MyTemplateProps) => `Subject for ${props.name}`
MyTemplate.preheader = (props: MyTemplateProps) => `Preheader for ${props.name}`
```

Do you think that would work for your use-case? If so, I think we should just add it. Will be pretty quick.

---

The POST functionality is interesting but a bit complicated to solve in a general way and maybe off the happy path. The happy path for using mailing templates is `sendMail` because you can use dynamic props at runtime. As a workaround, you could write a script that used `npx mailing export-previews` to export previews and then POSTs them to your endpoint. Adding an official solution is not off the table by any means, but I want to understand the problem better first.

- Is there a reason you're not using `sendMail` rather than copying the HTML into another system?
- What's the CMS and CRM you're using?

Thanks again!

**Comment by jbtheard** [comment]
Hi, sorry I have been ooo for a few days; 
Thanks for releasing that! I still have in mind to write/isolate a "starter kit" project for Dato CMS  + Mailing + Customer.io to illustrate how we've integrated Mailing in our flow. But more likely towards the end of the month...

**Comment by jbtheard** [comment]
fyi, our CRM (customer.io) does not currently support posting templates via rest so I guess I'll still have to do that manually anyways; and yes, a script would do as well...

**Comment by psugihara** [comment]
awesome, would love to check that out if you end up doing it.
