### ISSUE TITLE
Is it possible to use .env files?

### ISSUE THREAD

**Issue by cymen** [sofn-xyz/mailing#89]
I have a project with a `.env` file in the root and I use `import "dotenv/config";` to load the `.env` to `process.env`. I didn't realize it at first but this is not working with `email/index.ts` as the env values I'd expect to be defined (present in my `.env`) are not set on `process.env`.

**Comment by psugihara** [comment]
Hm, I'm guessing what's happening here is that you're seeing this behavior when sending from the mailing UI because the `import "dotenv/config";` is somewhere else in your app. Could that be the case?

If you add it to the top of `email/index.ts` does it work?

**Comment by psugihara** [comment]
That said, I think this is probably common enough that mailing should include `dotenv/config` internally and run it on every CLI command.

**Comment by cymen** [comment]
I was actually adding the `import "dotenv/config";` to the top of `emails/index.ts` (I kept writing `email` as the directory above but was tired last night -- I'm using the default locations).

Oddly enough today it is all working. I thought it was due to `isolatedModules` in my root `tsconfig.json` as mentioned in https://github.com/successor-software/mailing/issues/90 but I'm flipping that on and off and it doesn't make a difference now.

There isn't anything compiled/cached between `npx mailing` runs is there? If not, it seems like there was some kind of glitch yesterday that I'm not seeing at all today.

**Comment by cymen** [comment]
I edited `emails/index.ts` to change the contents of a `console.log` and it's updating without restarting (wasn't sure if that would be the case) so I'd chalk this up to some kind of odd edge case.

I'll keep trying to reproduce as I use `mailing` but I'm fine with closing this out and can reopen if I can get it to happen again. Sorry for what amounts to noise at the moment.

On a side note, really happy to find `mailing` -- thank you for sharing it. I was already using `MJML` but had a email template compile step and previewing wasn't as nice as I'd like plus I wasn't using `react-mjml` yet as it didn't fit well in my workflow. But I'm excited to be able to use all of that and have the excellent preview capabilities of `mailing`!

**Comment by psugihara** [comment]
> There isn't anything compiled/cached between npx mailing runs is there? If not, it seems like there was some kind of glitch yesterday that I'm not seeing at all today.

Nope, at this point everything is in memory. 

I think adding dotenv to the CLI so that people don't have to import it themselves is a good simplification, so I appreciate the issue.

Excited `mailing` is useful for you. If you have a minute, you mind telling us a little bit about how you plan to use it and your email stack? Just trying to learn about users so we can figure out what to iron out + how else we can ship to support devs sending email.

**Comment by cymen** [comment]
Sure, I'll send an email about my usage and adding dotenv by default sounds great!

**Comment by bruceharrison1984** [comment]
Just wanted to add this is a great feature to build in. I had to slightly tweak mine because I use a file with a different name:
```ts
import * as dotenv from 'dotenv';
import { buildSendMail } from 'mailing-core';
import nodemailer from 'nodemailer';

dotenv.config({
  path: '.env.local',
  debug: true,
});
```

Using `debug` helped me figure out that due to the way I have `tsconfig` setup, by base path is the root of the repo, and not the location of `emails/index.ts`.

Great job on this, looking forward to see where it goes!
